const predefinedCategories = [
    { title: 'Данъци и такси', description: 'Разходи за данъци и такси', predefined: true },
    { title: 'Джобни', description: 'Разходи за джобни', predefined: true },
    { title: 'Деца', description: 'Разходи свързани с децата', predefined: true },
    { title: 'Домашни любимци', description: 'Аксесоари, храна и ветеринарни услуги', predefined: true },
    { title: 'Доставка на храна', description: 'Разходи за доставка на храна', predefined: true },
    { title: 'Забавления', description: 'Разходи за забавления', predefined: true },
    { title: 'Застраховки', description: 'Застрахователни разходи', predefined: true },
    { title: 'Интернет', description: 'Интернет услуги', predefined: true },
    { title: 'Ипотека', description: 'Ипотечни вноски', predefined: true },
    { title: 'Кабелна телевизия', description: 'Кабелна телевизия', predefined: true },
    { title: 'Наем', description: 'Наемни разходи', predefined: true },
    { title: 'Отопление', description: 'Отоплителни разходи', predefined: true },
    { title: 'Паркинг', description: 'Разходи за паркинг', predefined: true },
    { title: 'Пътувания', description: 'Разходи за пътувания', predefined: true },
    { title: 'Продукти за вкъщи', description: 'Разходи за продукти за вкъщи', predefined: true },
    { title: 'Ресторанти', description: 'Разходи за посещение на ресторанти', predefined: true },
    { title: 'Телефон', description: 'Телефонни разходи', predefined: true },
    { title: 'Транспорт', description: 'Гориво, обществен транспорт и паркиране', predefined: true },
    { title: 'Финанси и застраховка', description: 'Данъци, застраховки и финансови разходи', predefined: true },
    { title: 'Храна', description: 'Доставка на храна, продукти за вкъщи и ресторантни услуги', predefined: true },
    { title: 'Здраве', description: 'Лекарства, медицински прегледи и здравни разходи', predefined: true },
    { title: 'Лични разходи', description: 'Дрехи, обувки, забавления, козметика и пътувания', predefined: true },
    { title: 'Образование', description: 'Курсове, учебни материали и такси за образование', predefined: true },
    { title: 'Други', description: 'Разходи, които не попадат в другите категории', predefined: true },
];

module.exports = predefinedCategories;